CREATE TABLE Vocabulary (
    VocabularyID INT IDENTITY(1,1) PRIMARY KEY,
    Word NVARCHAR(100) NOT NULL UNIQUE,
    Definition NVARCHAR(MAX),
    Example NVARCHAR(MAX),
    Language NVARCHAR(50) NOT NULL,
    DateAdded DATETIME DEFAULT GETDATE()
);
