package com.mycompany.englishlearningapp.Interface;

// Container - height = 680;
//             width = 1040;
import com.mycompany.englishlearningapp.Database.UserController;
import com.mycompany.englishlearningapp.Proccess.User;
import java.awt.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DashBoard extends javax.swing.JFrame {

    private javax.swing.JButton currentActiveButton;
    private User currentUser = new User();
    
    public DashBoard(String userName) throws SQLException {
        setTitle("English Learning App - " + userName);
        this.currentUser = UserController.getUserByName(userName);
        
        initComponents();

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize(); // Lấy kích thước màn hình
        int x = (screenSize.width - getWidth()) / 2; // Tính tọa độ x
        int y = (screenSize.height - getHeight()) / 2; // Tính tọa độ y
        setLocation(x, y); // Đặt vị trí cửa sổ ở giữa màn hình

        setActiveButton(btnHome);
        showPanel("PanelHome");

        pnContainer.setLayout(new CardLayout());
        pnContainer.setPreferredSize(Style.PANEL_DEFAULT_SIZE);
        pnContainer.setMinimumSize(Style.PANEL_DEFAULT_SIZE);
        pnContainer.setMaximumSize(Style.PANEL_DEFAULT_SIZE);

        pnContainer.add(new PanelHome(currentUser), "PanelHome");
        pnContainer.add(new PanelLibrary(currentUser), "PanelLibrary");
        pnContainer.add(new PanelLearning(), "PanelLearning");
        pnContainer.add(new PanelStatistic(), "PanelStatistic");
    }
    
    public DashBoard () throws SQLException {
        this("Guest");
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBackground = new javax.swing.JPanel();
        pnContainer = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnLibrary = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnLearnVoc = new javax.swing.JButton();
        txtIcon = new javax.swing.JLabel();
        btnStatistic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnBackground.setBackground(new java.awt.Color(198, 231, 255));
        pnBackground.setPreferredSize(new java.awt.Dimension(1220, 680));

        pnContainer.setBackground(new java.awt.Color(251, 251, 251));
        pnContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(198, 231, 255)));
        pnContainer.setPreferredSize(new java.awt.Dimension(1040, 680));
        pnContainer.setLayout(new java.awt.CardLayout());

        pnMenu.setBackground(new java.awt.Color(251, 251, 251));
        pnMenu.setPreferredSize(new java.awt.Dimension(180, 680));

        btnHome.setBackground(new java.awt.Color(251, 251, 251));
        btnHome.setFont(new java.awt.Font("Cascadia Mono", 0, 16)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\EnglishLearningApp\\src\\main\\Resources\\Image\\icons8-home\\icons8-home-30.png")); // NOI18N
        btnHome.setText("Trang chủ");
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setIconTextGap(10);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnLibrary.setBackground(new java.awt.Color(251, 251, 251));
        btnLibrary.setFont(new java.awt.Font("Cascadia Mono", 0, 16)); // NOI18N
        btnLibrary.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\EnglishLearningApp\\src\\main\\Resources\\Image\\icons8-book-shelf\\icons8-book-shelf.png")); // NOI18N
        btnLibrary.setText("Thư viện");
        btnLibrary.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLibrary.setIconTextGap(10);
        btnLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibraryActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(251, 251, 251));
        btnLogOut.setFont(new java.awt.Font("Cascadia Mono", 0, 16)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\EnglishLearningApp\\src\\main\\Resources\\Image\\icons8-logout\\icons8-logout-30.png")); // NOI18N
        btnLogOut.setPreferredSize(new java.awt.Dimension(50, 50));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnLearnVoc.setBackground(new java.awt.Color(251, 251, 251));
        btnLearnVoc.setFont(new java.awt.Font("Cascadia Mono", 0, 16)); // NOI18N
        btnLearnVoc.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\EnglishLearningApp\\src\\main\\Resources\\Image\\icons8-flashcards\\icons8-flashcards-30.png")); // NOI18N
        btnLearnVoc.setText("Học từ");
        btnLearnVoc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLearnVoc.setIconTextGap(10);
        btnLearnVoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearnVocActionPerformed(evt);
            }
        });

        txtIcon.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\EnglishLearningApp\\src\\main\\Resources\\Image\\icons8-hoyolab-cute-color\\icons8-hoyolab-80.png")); // NOI18N
        txtIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(198, 231, 255)));

        btnStatistic.setBackground(new java.awt.Color(251, 251, 251));
        btnStatistic.setFont(new java.awt.Font("Cascadia Mono", 0, 16)); // NOI18N
        btnStatistic.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\EnglishLearningApp\\src\\main\\Resources\\Image\\icons8-statistic-basic-outline\\icons8-graph-30.png")); // NOI18N
        btnStatistic.setText("Thống kê");
        btnStatistic.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStatistic.setIconTextGap(10);
        btnStatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(txtIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(btnLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLearnVoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnStatistic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtIcon)
                .addGap(20, 20, 20)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLearnVoc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout pnBackgroundLayout = new javax.swing.GroupLayout(pnBackground);
        pnBackground.setLayout(pnBackgroundLayout);
        pnBackgroundLayout.setHorizontalGroup(
            pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnBackgroundLayout.setVerticalGroup(
            pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBackgroundLayout.createSequentialGroup()
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                    .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        getContentPane().add(pnBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showPanel(String panelName) {
        CardLayout layout = (CardLayout) pnContainer.getLayout();
        layout.show(pnContainer, panelName);
    }

    private void setActiveButton(javax.swing.JButton button) {
        if (currentActiveButton != null) {
            currentActiveButton.setBackground(Style.BACKGROUND_COLOR);
            currentActiveButton.setForeground(Color.BLACK);
        }

        button.setBackground(Style.ACTIVE_BG_COLOR);
        button.setForeground(Style.ACTIVE_FONT_COLOR);

        currentActiveButton = button;
    }

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        Login loginForm = new Login();
        loginForm.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibraryActionPerformed
        setActiveButton(btnLibrary);
        showPanel("PanelLibrary");
    }//GEN-LAST:event_btnLibraryActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        setActiveButton(btnHome);
        showPanel("PanelHome");
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnLearnVocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearnVocActionPerformed
        setActiveButton(btnLearnVoc);
        showPanel("PanelLearning");
    }//GEN-LAST:event_btnLearnVocActionPerformed

    private void btnStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticActionPerformed
        setActiveButton(btnStatistic);
        showPanel("PanelStatistic");
    }//GEN-LAST:event_btnStatisticActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new DashBoard().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLearnVoc;
    private javax.swing.JButton btnLibrary;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnStatistic;
    private javax.swing.JPanel pnBackground;
    private javax.swing.JPanel pnContainer;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JLabel txtIcon;
    // End of variables declaration//GEN-END:variables
}
