package com.mycompany.englishlearningapp.Interface;

import com.mycompany.englishlearningapp.Database.UserController;
import com.mycompany.englishlearningapp.Proccess.User;
import java.text.SimpleDateFormat;
import java.util.Date;

public class PanelProfile extends javax.swing.JPanel {

    private User currentUser = new User();
    private UserController userController = new UserController();
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");

    public PanelProfile(User user) {
        currentUser = user;

        Date joinDate = currentUser.getDateCreated();
        String formattedJoinDate = dateFormat.format(joinDate);;
        
        Date changePassDate = currentUser.getDateChangedPass();
        String formattedChangePassDate = dateFormat.format(changePassDate);;
        
        initComponents();

        txtUserID.setText(" " + String.valueOf(currentUser.getUserID()));
        txtUserName.setText(" " + currentUser.getUsername());
        txtEmail.setText(" " + currentUser.getEmail());
        txtJoinDay.setText(" " + formattedJoinDate);
        txtLastPassChanged.setText(" " + formattedChangePassDate);
    }

    public PanelProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnProfile = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblProfile = new javax.swing.JLabel();
        pnContainer = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblJoinDay = new javax.swing.JLabel();
        btnChangePass = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtJoinDay = new javax.swing.JTextField();
        lblLastPassChanged = new javax.swing.JLabel();
        txtLastPassChanged = new javax.swing.JTextField();
        lblUserID = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1040, 680));

        pnProfile.setBackground(new java.awt.Color(254, 250, 246));
        pnProfile.setPreferredSize(new java.awt.Dimension(1040, 680));

        jPanel4.setBackground(new java.awt.Color(251, 251, 251));
        jPanel4.setPreferredSize(new java.awt.Dimension(372, 50));

        lblProfile.setFont(new java.awt.Font("Cascadia Code", 1, 30)); // NOI18N
        lblProfile.setText("HỒ SƠ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(lblProfile)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(lblProfile)
                .addContainerGap())
        );

        pnContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnContainer.setPreferredSize(new java.awt.Dimension(950, 500));

        lblUserName.setFont(new java.awt.Font("Cascadia Code", 1, 20)); // NOI18N
        lblUserName.setText("Tên đăng nhập: ");

        lblEmail.setFont(new java.awt.Font("Cascadia Code", 1, 20)); // NOI18N
        lblEmail.setText("Email: ");

        lblJoinDay.setFont(new java.awt.Font("Cascadia Code", 1, 20)); // NOI18N
        lblJoinDay.setText("Ngày tham gia:");

        btnChangePass.setFont(new java.awt.Font("Cascadia Code", 0, 20)); // NOI18N
        btnChangePass.setText("Đổi mật khẩu");
        btnChangePass.setPreferredSize(new java.awt.Dimension(200, 40));
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        txtUserName.setFont(new java.awt.Font("Cascadia Code", 0, 20)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Cascadia Code", 0, 20)); // NOI18N

        txtJoinDay.setFont(new java.awt.Font("Cascadia Code", 0, 20)); // NOI18N

        lblLastPassChanged.setFont(new java.awt.Font("Cascadia Code", 1, 20)); // NOI18N
        lblLastPassChanged.setText("Lần cuối đổi mật khẩu: ");

        txtLastPassChanged.setFont(new java.awt.Font("Cascadia Code", 0, 20)); // NOI18N

        lblUserID.setFont(new java.awt.Font("Cascadia Code", 1, 20)); // NOI18N
        lblUserID.setText("Mã người dùng: ");

        txtUserID.setFont(new java.awt.Font("Cascadia Code", 0, 20)); // NOI18N

        javax.swing.GroupLayout pnContainerLayout = new javax.swing.GroupLayout(pnContainer);
        pnContainer.setLayout(pnContainerLayout);
        pnContainerLayout.setHorizontalGroup(
            pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContainerLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnContainerLayout.createSequentialGroup()
                            .addComponent(lblUserID)
                            .addGap(20, 20, 20)
                            .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnContainerLayout.createSequentialGroup()
                            .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblEmail)
                                .addComponent(lblUserName)
                                .addComponent(lblJoinDay, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEmail)
                                .addGroup(pnContainerLayout.createSequentialGroup()
                                    .addComponent(txtJoinDay, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addGap(200, 200, 200))
                                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnContainerLayout.createSequentialGroup()
                        .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnContainerLayout.createSequentialGroup()
                                .addComponent(lblLastPassChanged)
                                .addGap(20, 20, 20)
                                .addComponent(txtLastPassChanged, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(200, 200, 200)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        pnContainerLayout.setVerticalGroup(
            pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContainerLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserID)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJoinDay)
                    .addComponent(txtJoinDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastPassChanged)
                    .addComponent(txtLastPassChanged, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnProfileLayout = new javax.swing.GroupLayout(pnProfile);
        pnProfile.setLayout(pnProfileLayout);
        pnProfileLayout.setHorizontalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(pnContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnProfileLayout.setVerticalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code  here:
       
        
    }//GEN-LAST:event_btnChangePassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblJoinDay;
    private javax.swing.JLabel lblLastPassChanged;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnContainer;
    private javax.swing.JPanel pnProfile;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtJoinDay;
    private javax.swing.JTextField txtLastPassChanged;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
