package com.mycompany.englishlearningapp.Interface;

import com.mycompany.englishlearningapp.Database.UserController;
import com.mycompany.englishlearningapp.Database.VocabularyController;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import com.mycompany.englishlearningapp.Interface.AddVocabulary;

public class PanelLibrary extends javax.swing.JPanel {

    final VocabularyController voc = new VocabularyController();
    private final DefaultTableModel tableModel = new DefaultTableModel();
    private UserController currentUser = new UserController();
    private int userID;
    
    public PanelLibrary(String Username) throws SQLException {
        this.currentUser = UserController.getUserByName(Username);
        this.userID = currentUser.getUserID();
        
        initComponents();
        
        String[] colsName = {"Từ mới", "Định nghĩa", "Ví dụ"};
        tableModel.setColumnIdentifiers(colsName);

        tblVocabulary.setModel(tableModel);

        ShowData(userID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnModify = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVocabulary = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 247, 209));
        jPanel1.setPreferredSize(new java.awt.Dimension(1040, 680));

        btnModify.setBackground(new java.awt.Color(254, 250, 246));
        btnModify.setFont(new java.awt.Font("Cascadia Code", 0, 16)); // NOI18N
        btnModify.setText("Chỉnh sửa");
        btnModify.setPreferredSize(new java.awt.Dimension(200, 50));
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        tblVocabulary.setFont(new java.awt.Font("Cascadia Code", 0, 16)); // NOI18N
        tblVocabulary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Từ mới", "Định nghĩa", "Ví dụ"
            }
        ));
        jScrollPane1.setViewportView(tblVocabulary);
        if (tblVocabulary.getColumnModel().getColumnCount() > 0) {
            tblVocabulary.getColumnModel().getColumn(1).setMinWidth(100);
            tblVocabulary.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblVocabulary.getColumnModel().getColumn(2).setMinWidth(350);
            tblVocabulary.getColumnModel().getColumn(2).setPreferredWidth(350);
        }

        jLabel1.setFont(new java.awt.Font("Cascadia Code", 0, 20)); // NOI18N
        jLabel1.setText("Danh sách từ mới của bạn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        try {
            AddVocabulary addForm = new AddVocabulary();

            // Cập nhật lại bảng sau khi thêm hoặc chỉnh sửa từ vựng
            addForm.setCallBack(() -> {
                try {
                    ShowData(userID);  // Cập nhật lại bảng với dữ liệu mới
                } catch (SQLException ex) {
                    Logger.getLogger(PanelLibrary.class.getName()).log(Level.SEVERE, null, ex);
                }
            });

            addForm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PanelLibrary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void ShowData(int userID) throws SQLException {
        List<VocabularyController> lst = voc.GetVocabByUser(userID);
        ClearData();
        for (VocabularyController obj : lst) {
            String rows[] = {obj.getWord(), obj.getDefinition(), obj.getExample()};
            tableModel.addRow(rows);
        }
    }

    private void ClearData() throws SQLException {
        int n = tableModel.getRowCount() - 1;
        for (int i = n; i >= 0; i--) {
            tableModel.removeRow(i);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVocabulary;
    // End of variables declaration//GEN-END:variables
}
